# Generated by Django 6.1 on 2026-09-11 15:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('git_link', models.URLField()),
                ('other_link', models.URLField()),
                ('description', models.TextField()),
                ('started_at', models.DateField(default=django.utils.timezone.now)),
                ('ended_at', models.DateField(null=True)),
            ],
        ),
    ]
