# Generated by Django 5.2.17 on 2026-09-27 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
